### ISSUE TITLE
Video Files Not Downloading Correctly

### ISSUE THREAD

**Issue by Majoraslayer** [Monschichi/plex_downloader#77]
I have the script running as intended, and it is successfully scanning the files it needs to download.  However, the resulting video files are each only 85 bytes in size.  Does the script need to be updated to access the video files correctly for download?

**Comment by Monschichi** [comment]
I've released a new version, apparently Plex now only allows download when the server has Plex Pass and downloads enabled. Else I need to fall back to transcoding for download.

**Comment by Majoraslayer** [comment]
> I've released a new version, apparently Plex now only allows download when the server has Plex Pass and downloads enabled. Else I need to fall back to transcoding for download.

Thanks for the speedy investigation and bug fix!

**Comment by Majoraslayer** [comment]
> I've released a new version, apparently Plex now only allows download when the server has Plex Pass and downloads enabled. Else I need to fall back to transcoding for download.

I just tested the update with --progress enabled.  The progress bar jumped immediately to 100% with 0.0 bytes grabbed, no errors indicated.  However, it no longer grabs invalid files.  Is this the intended function when downloading from a downloading-disabled server, or should it be grabbing a file through transcoding?

**Comment by Majoraslayer** [comment]
The fix did eliminate downloading invalid files, but instead I got an
instant 100% progress bar with no files.  Is the transcoding download
supposed to be working in this update, or is it a proposal for a future
update?

**Comment by Monschichi** [comment]
Transcoding should work in this update. But I found a broken code line and fixed it.
Can you please try again?

**Comment by Majoraslayer** [comment]
I've done some more testing, and this does seem to work much better.  The
version from earlier today was spitting out errors, but if I ran the script
twice it would create the download folder on the first try and successfully
grab the file on the second try.  This update seems to have fixed those
errors altogether.

For my test of this latest version, I used it to download a file from my
known server that has downloads turned off.  It was successfully able to
grab the video through transcoding as described.  However, I may have found
the source of the problems I'm having; both of the other servers I've
tested use Rclone to mount Google Drive as a media source.  In both cases,
the script seems unable to grab the media file.  Server setups like this
tend to have a longer buffer time before videos start to play; I suspect
the script doesn't allow for that extra time, and it gives up before Rclone
and Plex server can buffer the file.  Would it be possible to get the
script to wait longer for the file to be accessed?

If it would help with your testing, we can share our Plex server to you
that uses this Rclone mounting setup.

**Comment by Monschichi** [comment]
I've added a `--timeout` parameter which defaults to 300 seconds. Can you please try if it now works if you raise it appropriately?

**Comment by Majoraslayer** [comment]
I set it as high as --timeout 30000 and it still seems to jump to 0 bytes
retrieved and stop at the same speed.  I wonder if it would be possible to
integrate a pause and wait timer to give the Plex server itself longer to
access it's own files? If the script itself and/or the PlexAPI is just
allowing longer for a response from the server, the server may respond fast
enough but isn't feeding file data fast enough for the script to be able to
grab anything.

**Comment by Monschichi** [comment]
I'll have a look at the API if there are some options which can be tweaked.

> If it would help with your testing, we can share our Plex server to you that uses this Rclone mounting setup.

If you want you can add `Monschichi` this could indeed help the testing.

**Comment by Majoraslayer** [comment]
You should have access to our server, pending your verification. The server
name is JEFFLIX. For testing I've been using "8-Bit Christmas" in the
"Movies" section.

**Comment by Monschichi** [comment]
Found the issue and fixed it. the script tried to resume even when it wasn't supposed to.
In my tests it worked now. @Majoraslayer Can you please verify?

**Comment by Majoraslayer** [comment]
My command line I'm using to test is as follows:

python3 /home/seedit4me/PlexDownloader/downloader.py --server "JEFFLIX"
--target "DownloaderTest" --section "Movies" --name "8-Bit Christmas"
---progress

After updating the script, I now seem to be getting a 502 server error
being thrown at PlexAPI.  I tested with another machine, installing the
script from scratch and using a different Plex login, and I got the same
result.  Probably irrelevant, but I'll advise it anyway since it was part
of my testing process: adding --timeout 30000 seems to make no difference
in this situation.

**Comment by Monschichi** [comment]
That's strange, the exact command line works for me without a problem.
Which Python version are you using?
Can you provide the full error message?

**Comment by Majoraslayer** [comment]
I just got a chance to try it again, and it appears to be working now.  The
error had a reference to a 500 server error from Plex.tv, so I'm hoping it
was just a temporary issue on Plex's end.  I'll keep playing around with
it, but things look promising.  If I run into another error I'll let you
know.  Thanks for working so hard on this!

**Comment by Majoraslayer** [comment]
So, I already need to follow up.  I was able to download on the first
attempt, but after one download it no longer works.  There are no errors
now, but below is my output.  I tried setting a different login within
.netrc that has access to the same Plex server and I was able to
successfully download file again.  On a second attempt, I get the same
result as below.  After switching the login back over in .netrc, the first
login is still unable to download.  Is something not terminating correctly
in the PlexAPI session?

[image: image.png]

**Comment by Monschichi** [comment]
That's intended. On a completed download the file is marked watched. And already watched files are not downloaded again. This is to easy keep up with series where you normally only want to download the new episodes, as you already have downloaded older episodes.
there are two possible solutions:
1. mark the file unwatched.
2. use the parameter `--force`, which ignores the watched status and downloads anyway.

**Comment by Majoraslayer** [comment]
Oh, that makes sense!  I used --force, and it works as intended.  Thanks a
ton!
