### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by ozdek** [Monschichi/plex_downloader#79]
Thank you for this lovely piece of work.

I have tried to download some stuff from a server I have access to and I have noticed some issues. I would like to make some feature requests if it is possible at all. I have no experience in programming so some of these might be weird. Apologies in advance for that.

1. A file name filter (with includes and excludes). Example: Do not include if "REMUX" in the file name and log it to a file to review it later.
2. A size filter ( greater than x or the opposite). Example: Do not download files if over 30 GB and log it to a file to review it later. And if it is possible use it as a file list to download later if I change my mind?
3. A temporary location (configurable) for downloading files and moving them only after the download is finished. I have noticed you are adding "." in front of the file names but my uploader script swipes all files to my server even if they are 10 MB or so. Those "." files are there because of the failed downloads. 
4.  Further logging to examine which files failed and why? I log all output to a file but my playlist consists of 30.000 items and it is a bit difficult to track. I can always rerun the script of course but I would like to know how much bw is wasted?
5.  A decision mechanism for episodes which have multiple files. Example: Tv Show S01E01 has 720p, 1080p and Remux versions. Do not download 720p & Remux ones (based on my choices). I appreciate that not all servers do have those in the filename but some flexibility would be good? This one might be difficult to implicate I get that. This is also linked with the first request as if there are only REMUX files for that episode log it somewhere and give me a chance to download them even if they are all REMUX.

**Comment by Monschichi** [comment]
Number 5 could be a bit tricky, the rest should be possible.
I'll have a closer look once it's raining again. If anyone else would like to try in the meantime pull requests are welcome.

**Comment by Monschichi** [comment]
I'll no longer maintain this project, so this issue will be closed. If someone want to continue maintaining it please contact me.
