### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by julio8a** [Monschichi/plex_downloader#82]
I have 500MB download and 500MB upload speeds. 
I'm downloading from a Friend's plex media server, who has 1GB up and down. 

However, the download speed is always under 20MB.

My speed test:
```
   Speedtest by Ookla

     Server: Nitel - Los Angeles, CA (id = 12191)
        ISP: Frontier Communications
    Latency:     4.82 ms   (1.22 ms jitter)
   Download:   473.31 Mbps (data used: 243.1 MB )
     Upload:   494.73 Mbps (data used: 899.3 MB )
Packet Loss:     0.0%
```

It must be something with the app? Any downloads outside are fine and fast. Running plex_downloader on Ubuntu

**Comment by Monschichi** [comment]
Did it says that it's downloading via transcoding? If so it would explain the slow speed.
Another possibility is that the plex server has it's download speed limited.
If you don't use the `--bwlimit` option the app uses the available speed and has no throttling.

**Comment by julio8a** [comment]
Thanks for the response. I think it was an issue outside of plex_downloader. I rebooted my system and it's not at around 200MB, which is much better.
